### ISSUE TITLE
Grabbing the client and gently tossing it around crashes the client

### ISSUE THREAD

**Issue by NatoBoram** [mmtrt/leagueoflegends#14]
Title. I moved the client around while it was doing its first update to observe a tearing issue, then it crashed.

```yaml
OS: Ubuntu 18.10 x86_64 
Kernel: 4.18.0-12-generic 
Uptime: 45 mins 
Packages: 2215 (dpkg), 41 (snap) 
Shell: bash 4.4.19 
Resolution: 1920x1080 
DE: GNOME 3.30.1 
WM: GNOME Shell 
WM Theme: Adwaita 
Theme: Adwaita-dark [GTK2/3] 
Icons: Yaru [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i5-3570K (4) @ 3.800GHz 
GPU: NVIDIA GeForce GTX 660 Ti 
Memory: 5673MiB / 7921MiB 
```
