### ISSUE TITLE
Unable to connect to the authentication service

### ISSUE THREAD

**Issue by aleksandar-babic** [mmtrt/leagueoflegends#153]
Hi,

I'm able to start the client (only after removing `/home/$USER/snap/leagueoflegends/common/.wine/drive_c/Riot Games/Riot Client`), but once I try to login I get following error:

![image](https://user-images.githubusercontent.com/20382381/94668970-f59d0300-0310-11eb-9121-e32a1e2d9592.png)

Any ideas?

Thanks!

**Comment by mmtrt** [comment]
Try this,

https://github.com/mmtrt/leagueoflegends/issues/150#issuecomment-700050456

**Comment by aleksandar-babic** [comment]
@mmtrt 

```yaml
install:
    crash_reporting:
        type: "crashpad"
    globals:
        locale: "en_GB"
        region: "EUNE"
    lcu-settings:
        accountId: 0
        modified: true
        timestamp: 0
    npe-splash:
        enableNewPlayerSplash: true
    patcher:
        client_migrated: true
        client_patcher_available: true
        client_patcher_migrated_time: "2020-09-30T09:22:08Z"
        game_migrated: true
        game_patcher_available: true
        game_patcher_migrated_time: "2020-09-30T09:22:08Z"
        locales:
        - "en_GB"
        - "en_US"
        toggles:
            new_client_patcher: 0
            new_game_patcher: 0
    rso-auth:
        install-identifier: "ac7904e39bc4454c9f5ebd6c6dcde464"
    telemetry:
        fresh_installation: false
        installation_id: "KXMuIg=="
```

I don't have that key at all in the config, where to put it ?
