### ISSUE TITLE
Is the client for Korean server not supported?

### ISSUE THREAD

**Issue by valotam** [mmtrt/leagueoflegends#88]
The Korean server installer was missing.
Can you add the URL of installer for Korean server?

---

**URLs are found on `snap.yaml` in the `/snap/leagueoflegends/53/meta` directory.**

```
apps:
  leagueoflegends:
    command: snap/command-chain/snapcraft-runner $SNAP/command-leagueoflegends.wrapper
    environment:
      DLLOVERRIDES: mscoree,mshtml=
      INSTALL_URL_BR: https://riotgamespatcher-a.akamaihd.net/releases/live/installer/deploy/League%20of%20Legends%20installer%20BR.exe
      INSTALL_URL_EUNE: https://riotgamespatcher-a.akamaihd.net/releases/live/installer/deploy/League%20of%20Legends%20installer%20EUNE.exe
      INSTALL_URL_EUW: https://riotgamespatcher-a.akamaihd.net/releases/live/installer/deploy/League%20of%20Legends%20installer%20EUW.exe
      INSTALL_URL_JP: https://riotgamespatcher-a.akamaihd.net/releases/live/installer/deploy/League%20of%20Legends%20installer%20JP.exe
      INSTALL_URL_LAN: https://riotgamespatcher-a.akamaihd.net/releases/live/installer/deploy/League%20of%20Legends%20installer%20LA1.exe
      INSTALL_URL_LAS: https://riotgamespatcher-a.akamaihd.net/releases/live/installer/deploy/League%20of%20Legends%20installer%20LA2.exe
      INSTALL_URL_NA: https://riotgamespatcher-a.akamaihd.net/releases/live/installer/deploy/League%20of%20Legends%20installer%20NA.exe
      INSTALL_URL_OCE: https://riotgamespatcher-a.akamaihd.net/releases/live/installer/deploy/League%20of%20Legends%20installer%20OC1.exe
      INSTALL_URL_PBE: https://riotgamespatcher-a.akamaihd.net/releases/pbe/installer/deploy/League%20of%20Legends%20installer%20PBE.exe
      INSTALL_URL_RU: https://riotgamespatcher-a.akamaihd.net/releases/live/installer/deploy/League%20of%20Legends%20installer%20RU.exe
      INSTALL_URL_TR: https://riotgamespatcher-a.akamaihd.net/releases/live/installer/deploy/League%20of%20Legends%20installer%20TR.exe
      LC_ALL: C.UTF-8
      TRICKS: d3dx9,winxp
      WINEPREFIX: $SNAP_USER_COMMON/.wine
```

**Korean installer's URL is** 

```
      INSTALL_URL_KR: https://riotgamespatcher-a.akamaihd.net/KR_CBT/installer/deploy/League%20of%20Legends%20installer%20KR.exe
```

Installation functions and codes are found on `sommelier` in the `/snap/leagueoflegends/53/bin` directory.
